-- Seed: GEC 2025 Indianapolis UK delegation (46 delegates)
-- Source: delegates-seed.csv prepared from the GEC 2025 UK Delegation Handbook.
-- Nulls are deliberate gaps in the source; category is a provisional first pass,
-- delegates correct their own on claim.

insert into public.delegates (cohort, slug, first_name, last_name, role, organisation, linkedin_url, category) values
('gec-2025','martine-abboud','Martine','Abboud','Founding Exec Director','CREO Incubator','https://www.linkedin.com/in/martineabboud','support_org'),
('gec-2025','steve-aicheler','Steve','Aicheler','Operations and Development Manager','Enterprise Educators UK','https://www.linkedin.com/in/steve-aicheler','education'),
('gec-2025','jerry-allen','Jerry','Allen','Director of Entrepreneurship','University College London','https://www.linkedin.com/in/jerryallen234','university'),
('gec-2025','khalid-altalib','Khalid','AlTalib','Co-Founder','Founden','https://www.linkedin.com/in/khalid-altalib','founder'),
('gec-2025','klauss-andrei','Klauss','Andrei','Captain','Kappa.London','https://www.linkedin.com/in/klaussa','founder'),
('gec-2025','tim-barnes','Tim','Barnes','CEO','Centre for Entrepreneurs','https://www.linkedin.com/in/timothyplbarnes','support_org'),
('gec-2025','oli-barrett','Oli','Barrett',null,null,'https://www.linkedin.com/in/olibarrett',null),
('gec-2025','fabio-bianchi','Fabio','Bianchi','Head of Entrepreneurship','Oxentia','https://www.linkedin.com/in/fabio-bianchi-b0796345','support_org'),
('gec-2025','adam-bradford','Adam','Bradford','CEO','Green Horizon Africa','https://www.linkedin.com/in/adambradford1','founder'),
('gec-2025','albert-bravo-biosca','Albert','Bravo-Biosca','Executive Director','Innovation Growth Lab','https://www.linkedin.com/in/abravobiosca','policy'),
('gec-2025','tim-brundle','Tim','Brundle','Director of Research and Impact','Ulster University','https://www.linkedin.com/in/timbrundle','university'),
('gec-2025','bruno-bugingo','Bruno','Bugingo','Advisor to CEO','Green Horizon Africa','https://www.linkedin.com/in/bruno-bugingo-022250198','founder'),
('gec-2025','kendra-byers','Kendra','Byers','Business Engagement and Communications Manager','Edinburgh Napier University','https://www.linkedin.com/in/kendrabyers','university'),
('gec-2025','gosbert-chagula','Gosbert','Chagula','Co-founder','Startup Discovery School','https://www.linkedin.com/in/gosbert','founder'),
('gec-2025','ben-chalmers','Ben','Chalmers','Cofounder CTO','Engaged Intelligence','https://www.linkedin.com/in/bchalmers','founder'),
('gec-2025','john-cockburn-evans','John','Cockburn-Evans','Cofounder CEO','Engaged Intelligence','https://www.linkedin.com/in/john-c-evans-change-agent','founder'),
('gec-2025','katie-coombes','Katie','Coombes','Lead Trainer','The Rebel School','https://www.linkedin.com/in/katiecoombesfacilitator','education'),
('gec-2025','clementine-flack','Clementine','Flack','Programme Manager, International Entrepreneurship','Royal Academy of Engineering','https://www.linkedin.com/in/clementineflack','support_org'),
('gec-2025','kaitlin-fritz','Kaitlin','Fritz','Medtech Program Manager','Capital Enterprise','https://www.linkedin.com/in/kaitlin-fritz','support_org'),
('gec-2025','paul-gooday','Paul','Gooday','Director of Exports, North America Network','Department for Business and Trade','https://www.linkedin.com/in/paul-sipho-gooday-05a88378','policy'),
('gec-2025','simon-goon','Simon','Goon','Chief Technology and Investment Officer','UMi','https://www.linkedin.com/in/simon-goon','support_org'),
('gec-2025','jo-gray','Jo','Gray','Director of Membership Services and Engagement','Youth Business International','https://www.linkedin.com/in/joannafgray','support_org'),
('gec-2025','chris-haley','Chris','Haley','Head of Research','Startup Genome','https://www.linkedin.com/in/cdhaley','research'),
('gec-2025','dom-hallas','Dom','Hallas','Executive Director','Startup Coalition','https://www.linkedin.com/in/dom-hallas','policy'),
('gec-2025','tom-hancock','Tom','Hancock','Research Associate','GEN','https://www.linkedin.com/in/tdhancock','gen'),
('gec-2025','mike-jackson','Mike','Jackson','Ecosystem Growth Advisory','Startup Genome','https://www.linkedin.com/in/mikedjackson','research'),
('gec-2025','ryan-johnson','Ryan','Johnson','Manager','Business & IP Centre Oxfordshire','https://www.linkedin.com/in/thinkyoung','support_org'),
('gec-2025','aaron-jones','Aaron','Jones','Founder','Yepic.ai','https://www.linkedin.com/in/aaronbenjaminjones','founder'),
('gec-2025','bindi-karia','Bindi','Karia','Partner','Bindi Ventures','https://www.linkedin.com/in/bindik','investor'),
('gec-2025','andrew-lindsay','Andrew','Lindsay','Senior Consultant','The Challenges Group',null,'support_org'),
('gec-2025','natalia-loza','Natalia','Loza','Co-Founder','CohortHQ','https://www.linkedin.com/in/nata-loza','founder'),
('gec-2025','dhruv-majumdar','Dhruv','Majumdar','Co-Founder and Director','Startium','https://www.linkedin.com/in/dhruvmajumdar','founder'),
('gec-2025','jonathan-mcalpin','Jonathan','McAlpin','Chair','Enterprise Northern Ireland','https://www.linkedin.com/in/jonathan-mcalpin-a3130625','support_org'),
('gec-2025','jo-mills','Jo','Mills','Head of Entrepreneurship','Wellcome Sanger Institute','https://www.linkedin.com/in/joannasmills','university'),
('gec-2025','gary-omeara','Gary','O''Meara','MD','GEN Ireland','https://www.linkedin.com/in/garyomeara','gen'),
('gec-2025','marc-ortmans','Marc','Ortmans','Chair','GEN UK','https://www.linkedin.com/in/marcortmans','gen'),
('gec-2025','miranda-page','Miranda','Page','Director of Comms','Youth Business International','https://www.linkedin.com/in/pagemiranda','support_org'),
('gec-2025','amy-potts','Amy','Potts','Senior Programme Manager','Enterprise Nation','https://www.linkedin.com/in/amyp-programmes','support_org'),
('gec-2025','peter-ptashko','Peter','Ptashko','CEO and Founder','Cambio Consultancy','https://www.linkedin.com/in/peter-ptashko-frsa','founder'),
('gec-2025','sushil-ram','Sushil','Ram','Advisor','Commonwealth Secretariat','https://www.linkedin.com/in/sushil-ram-02778069','policy'),
('gec-2025','christina-richardson','Christina','Richardson','Founder','Foundology','https://www.linkedin.com/in/christinarichardson13','founder'),
('gec-2025','josh-robson','Josh','Robson','Head of Public Affairs and External Relations','Scaleup Institute','https://www.linkedin.com/in/josh-robson-37434513','policy'),
('gec-2025','anna-sexton','Anna','Sexton','Founder','Open to Create','https://www.linkedin.com/in/open-to-create-anna-b-sexton','founder'),
('gec-2025','chris-shannon','Chris','Shannon','Founder','Startium','https://www.linkedin.com/in/chrisatstartium','founder'),
('gec-2025','emilee-simmons','Emilee','Simmons','President-Elect','Enterprise Educators UK','https://www.linkedin.com/in/emileesimmons','education'),
('gec-2025','matt-smith','Matt','Smith','Vice President','GEN','https://www.linkedin.com/in/matttp','gen');
