// Single place for every open item from the spec (§9).
// Fill these in and the whole site updates.

export const config = {
  // §9.1 — Author name for the title card and footer
  author: 'Priscilla Frimpong-Manso',

  // §9.2 — Price shown on the primary CTA
  price: '[PRICE]',

  // §10 — Books2Read Universal Book Link (auto-generated by Draft2Digital).
  // This is the primary CTA destination.
  universalBookLink: '#ubl-pending',

  // Per-retailer links for the secondary row (fill as listings go live)
  retailers: [
    { name: 'Amazon', href: '#amazon-pending' },
    { name: 'Apple Books', href: '#apple-pending' },
    { name: 'Kobo', href: '#kobo-pending' },
    { name: 'Google Play', href: '#gplay-pending' },
    { name: 'Selar', href: '#selar-pending' },
  ],

  // §9.3 — Email capture endpoint (form service or serverless function URL).
  // Leave empty to show the form in "not yet wired" mode.
  emailEndpoint: '',

  // §9.6 — Reader quotes. Leave empty and the block is omitted entirely — no fake reviews.
  testimonials: [
    // { quote: '…', name: '…' },
  ],

  // Social links for the footer (add Wattpad profile once the serial is live — §10.5)
  socials: [
    // { name: 'Instagram', href: '' },
    // { name: 'Wattpad', href: '' },
  ],

  // SEO
  title: 'Shadows in Our Home — read the first three chapters',
  description: "Zarek didn't believe in love at first sight. But he believed in moments.",
};
