// Single place for every open item from the spec (§9).
// Fill these in and the whole site updates.

export const config = {
  // §9.1 — Author name for the title card and footer
  author: 'Priscilla Frimpong-Manso',

  // Pre-publication mode: the book isn't live in any store yet, so the
  // primary CTA sends readers to the Chapter-4 email capture instead of a
  // dead buy link. Flip to false once the UBL/retailer links below are real.
  prelaunch: true,

  // §9.2 — Price shown on the primary CTA. Leave empty to show no price
  // (per Peter: no price until final, avoids wrong-currency for a mixed
  // Ghana/UK/US audience).
  price: '',

  // §10 — Books2Read Universal Book Link (auto-generated by Draft2Digital).
  // This is the primary CTA destination.
  universalBookLink: '#ubl-pending',

  // Per-retailer links for the secondary row (fill as listings go live)
  retailers: [
    { name: 'Amazon', href: '#amazon-pending' },
    { name: 'Apple Books', href: '#apple-pending' },
    { name: 'Kobo', href: '#kobo-pending' },
    { name: 'Google Play', href: '#gplay-pending' },
    { name: 'Selar', href: '#selar-pending' },
  ],

  // §9.3 — Email capture endpoint. An n8n webhook that appends each signup
  // to the "Shadows in Our Home — Signups" Google Sheet in Peter's Drive.
  emailEndpoint: 'https://kickstartglobal.app.n8n.cloud/webhook/shadows-signup',

  // §9.6 — Reader quotes. Leave empty and the block is omitted entirely — no fake reviews.
  testimonials: [
    // { quote: '…', name: '…' },
  ],

  // Social links for the footer (add Wattpad profile once the serial is live — §10.5)
  socials: [
    // { name: 'Instagram', href: '' },
    // { name: 'Wattpad', href: '' },
  ],

  // SEO
  title: 'Shadows in Our Home — read the first three chapters',
  description: "Zarek didn't believe in love at first sight. But he believed in moments.",
};
